# Generated by Django 5.2.12 on 2026-03-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
