# Generated by Django 5.2.12 on 2026-03-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_post_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_status',
            field=models.BooleanField(default=False),
        ),
    ]
